### ISSUE TITLE
Make pathway analysis optional

### ISSUE THREAD

**Issue by SusiJo** [qbic-pipelines/rnadeseq#102]
Hi there,

Currently, if no pathways can be found, the pipeline fails (see Issue #86). In such a case it would be nice to stop the pathway analysis process and jump directly to the next process that creates the output report. 
Also, it would be helpful to skip pathway analysis completely if that information is not needed. Maybe this could be implemented as a command-line flag `--skip_pathway_analysis`.

**Comment by d4straub** [comment]
Yes please allow skipping the pathway analysis, because for my bacteria/metagenome projects the pathway analysis doesnt work anyway! In that regard, `--species` might be good to make optional as well, if in the scope of this issue.

**Comment by ggabernet** [comment]
yup this will be added in the next release

**Comment by WackerO** [comment]
This feature was added in a recent PR, therefore I am closing this issue.
