### ISSUE TITLE
MultiQC now has a "-fw" in the sample name leading to duplicate lines

### ISSUE THREAD

**Issue by LaurenceKuhl** [qbic-pipelines/rnadeseq#114]
Hi there, 

recently, upon running rnaseq 1.3.2, the multiqc general stats ressembles this :
[multiqc_general_stats-2.txt](https://github.com/qbic-pipelines/rnadeseq/files/8341300/multiqc_general_stats-2.txt)
so we have for 1 sample 2 lines with different stats on each line.
This leads to also 2 lines  in the rnadeseq report in the general stats part.
You'll also find the software version used for rnaseq here [software_versions-2.csv](https://github.com/qbic-pipelines/rnadeseq/files/8341315/software_versions-2.csv).

Let me know if you have any other questions, best,
Laurence

**Comment by WackerO** [comment]
Solved in #165
