### ISSUE TITLE
Update to final report.zip

### ISSUE THREAD

**Issue by qbicStefanC** [qbic-pipelines/rnadeseq#119]
Currently the final report.zip contains the following files/folders:
.
├── offer_signed.pdf
├── QC
├── RNAseq_report.html
├── differential_gene_expression
└── pathway_analysis

However, the `pipeline_info/results_description.html` file should also be part of it, which is very useful to get an overview of the data generated in this workflow which can be also forwarded to PIs of projects.

**Comment by qbicStefanC** [comment]
Just realized that the file `pipeline_info/results_description.html` is quite out of date (e.g. still names a folder Deseq2 which is not existing anymore since a while. Updating this file might should go into a new issue. I will open one

**Comment by ggabernet** [comment]
We will consider if this is needed, if we manage to port the pipleline to nf-core

**Comment by WackerO** [comment]
As the results descriptions are now provided in the report and the pipeline has indeed been ported to nf-core, I'll close this issue.
