### ISSUE TITLE
Pathway analysis folder should not be created if pathway analysis was set to FALSE

### ISSUE THREAD

**Issue by qbicStefanC** [qbic-pipelines/rnadeseq#120]
I usually define pathway analysis in a yml file like given in the `testdata` here: https://github.com/qbic-pipelines/rnadeseq/blob/master/testdata/report_options.yml

If I change there the option to

```
KEGG: FALSE
```
and run it as usual with : 
`--report_options 'report_options.yml'`

I still get the `pathway_analysis` folder created. This should be changed.
Thanks

**Comment by ggabernet** [comment]
@WackerO will just check if the issue is still there in the new implementation, and if not just close it :)

**Comment by WackerO** [comment]
This is implemented now :)
