### ISSUE TITLE
Updating file `pipeline_info/results_description.html`

### ISSUE THREAD

**Issue by qbicStefanC** [qbic-pipelines/rnadeseq#121]
The file `pipeline_info/results_description.html` is very useful to hand directly to a PI of the project as it lists all files and folders in the rnadeseq report.
However this file is quite out of date. Is there a plan in the current development to update this description file as well? This might should be done before issue #119 .
Thanks

**Comment by WackerO** [comment]
Note: It seems this file is not produced anymore, I believe markdown_to_html.R was used to create it, and that script is not called anywhere

**Comment by WackerO** [comment]
-->Instead, I will see that the output is explained in the report itself so that people don't have to check an additional file

**Comment by WackerO** [comment]
Closed in #176
