### ISSUE TITLE
Add sample labels to PCA plot RNAseq_report.htm

### ISSUE THREAD

**Issue by jonoave** [qbic-pipelines/rnadeseq#143]
### Description of feature

Hi,

This is a feature request on behalf of @qbicStefanC and myself.

It would be quite useful and helpful to add individual sample labels directly on the PCA plots in the `RNAseq_report.html` file. As the colour coding used is on a gradient, differentiating and identifying the different samples are quite difficult. Furthermore the legend only states the main groups of the samples, not each individual sample

E.g. 

![image](https://user-images.githubusercontent.com/7349352/182588122-60d4c6f8-320a-44b3-9757-a5947fe818b1.png)

There are 23 samples here, categorised in 4 groups. Would it be possible to create an additional plot, .e.g: 
1. Current plot without sample labels.
2. Additional plot with sample labels in the plot itself. 

Thank you,
Jun-Hoe

**Comment by jonoave** [comment]
Hi,

Just to add a bit more context and details. Here's another project I'm working on: QTHER that has over 80 samples. Heres the output from the rnadeseq report. 

![image](https://user-images.githubusercontent.com/7349352/184154884-3e4bbc7d-7ad3-4062-acbe-e8e24f46712c.png)

Here it would be really useful to identify the few samples on the top right of the PCA plot

Unfortunately the heatmap isn't too helpful:

![image](https://user-images.githubusercontent.com/7349352/184155114-a02eb1d6-0597-4f63-9fd0-5c50ab6f18b4.png)

Due to the high amount of sample, all the sample labels are squished together so we can't tell what each sample label is.
If there's a way the plot or y/x-axes labels could be auto-scaled, that would be great.

Thank you,
Jun-Hoe

**Comment by WackerO** [comment]
Will add static PCA plots with and without labels to the output folders; the labeling inside the report should already be fine as the new reports have additional interactive stuff (including the PCA and heatmap!)

**Comment by WackerO** [comment]
Added static labeled plots in #188
