### ISSUE TITLE
Improve error message salmon input

### ISSUE THREAD

**Issue by SusiJo** [qbic-pipelines/rnadeseq#154]
### Description of feature

Hi,

when using the flag `--input_type salmon` the pipeline just stops when some `quant.sf` files are missing or cannot be found. When there's a typo in the `samplesheet.tsv`, it would be helpful to have a more specific error message than this one:

```
Exiting.
  Error: DESeq2.R could not find all of the specified quant.sf files!
  In addition: Warning message:
  In .local(x, row.names, optional, ...) : Arguments in '...' ignored
  Execution halted
```

If possible, it would be really helpful if the message could be more specific and point to the sample which it does not find. 

Another idea would be to create a samplesheet_generator script that also performs samplesheet validation.

**Comment by SusiJo** [comment]
Or maybe make a section in the docu that shares common error messages and how to troubleshoot.

**Comment by WackerO** [comment]
Changed the error message in #159, closing this
