### ISSUE TITLE
Volcano plots and PCA plot don't have correct x and y axis dimensions

### ISSUE THREAD

**Issue by LaurenceKuhl** [qbic-pipelines/rnadeseq#183]
### Description of the bug

Hi there,

when i run version 2.0.1 my volcano plots often are "squished" with incorrect x and y axis sizes, enclosed is an example.
Best,
Laurence
<img width="583" alt="Screenshot 2023-01-17 at 10 47 07" src="https://user-images.githubusercontent.com/11715835/212864923-74ffe119-e45e-4827-8aa5-59ca90c8ab8d.png">
Cheers,
Laurence

**Comment by WackerO** [comment]
I'm going to close this issue as in the current dev version, the plots look fine.
