### ISSUE TITLE
star salmon doesn't output round values

### ISSUE THREAD

**Issue by LaurenceKuhl** [qbic-pipelines/rnadeseq#187]
### Description of the bug

 I am trying to use the salmon gene counts as an input salmon.merged.gene_counts.tsv  but i’m getting

`
Warning messages:
1: package ?RColorBrewer? was built under R version 4.1.3 
2: package ?matrixStats? was built under R version 4.1.3 
3: package ?dplyr? was built under R version 4.1.3 
4: replacing previous import ?utils::download.file? by ?restfulr::download.file? when loading ?rtracklayer? 
Exiting.
Error in DESeqDataSet(se, design = design, ignoreRank) : 
  some values in assay are not integers
Calls: DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted`, size: 1099 (max: 255)`

### Command used and terminal output

```console
nextflow run qbic-pipelines/rnadeseq -r 2.0.1 -profile cfc --gene_counts 'results/star_salmon/salmon.merged.gene_counts.tsv' --metadata "ref/metadata.txt" --model "ref/linear_model.txt" --project_summary "ref/QMIRN_20221208151920_summary.tsv" --multiqc "results/multiqc/MultiQC.zip" --versions "ref/software_versions.csv" --genome "GRCh37" --organism "hsapiens"
```

### Relevant files

gene_id gene_name       SRX1831795      SRX1831796      SRX1831797      SRX1831798      SRX1831799      SRX1831800      SRX1831801      SRX1831802      SRX1831803      SRX1831804      SRX1831816      SRX1831817      SRX1831818      SRX1831819      SRX1831820      SRX1831821      SRX1831822      SRX1831823      SRX1831824      SRX1831825      SRX1831826      SRX1831827      SRX1831828      SRX1831829      SRX1831830      SRX1831831      SRX1831832      SRX1831833      SRX1831834      SRX1831835
ENSG00000000003 TSPAN6  2505    2373    2158    2755.001        3576.999        5674    5944    2947.999        3300    2708    2713.001        3650    1828    1538    2255    2170    5411.999        4946    3644    2945    1090.001        1059    998.001 1169    1045.999        1507.001        2433    2042    2031    1763.001
ENSG00000000005 TNMD    0       0       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0       0       0       0
ENSG00000000419 DPM1    2498    2522    2074    1699    2182.002        4549    4555    1986.999        2199    1822    3314.001        4774.999        2440.999        1491.001        2464    2331    6535.001        6249.999        4097.999        3306    2010    1901    1791    2004.001        1715    2708.001        2981.001        2428    2276    2298
ENSG00000000457 SCYL3   458.988 432.721 408.715 640.23  898.487 1174.555        1110.015        399.22  457.337 359.756 759.674 696.126 379.92  327.037 433.191 372.241 1579.332        1542.252        660.211 885.923 218.938 233.164 205.752 176.869 177.835 258.948 398.601 329.121 324.663 325.892
ENSG00000000460 C1orf112        1035.011        970.39  881.285 1367.77 1769.551        3121.444        3039.991        1165.78 1221.678        1114.244        1932.384        2697.872        1603.083        1105.962        1618.809        1583.759        4122.667        3269.749        2011.79 3335.076        803.064 721.836 681.248 484.132 378.166 597.053 1168.399        891.878 1220.335        965.109

**Comment by WackerO** [comment]
Hey, as https://support.bioconductor.org/p/116143/ advises to use the quant.sf files that salmon outputs in addition to its matrix, I suggest to do just that (in rnadeseq, this can be done by setting `--input_type salmon` and then just supplying the quant.sf folder instead of the matrix). I will keep this issue open though, in case someone finds that it is after all better to stick to the rounded matrix.

**Comment by WackerO** [comment]
Will close this now, reopen if there are any issues.
