### ISSUE TITLE
If no enriched pathway is found, it simply states so instead of throwing an error

### ISSUE THREAD

**Issue by jonoave** [qbic-pipelines/rnadeseq#210]
### Description of feature

The pipeline v.2.0.1 throws an error if there is no enriched pathway found (this pipeline always appear too optimistic :D ) 

E.g in the following run on 05.06.2023, run_ID: boring_linnaeus . It throws the following error

I reran it, but added the parameter: `--skip_pathway_analysis` (run_ID:  fabulous_joliot ) 
This run completed without errors.

**Comment by WackerO** [comment]
I'll close this as on master, this issue is already dealt with; when the next release comes out, you can use that version and then no error should be thrown :)
