### ISSUE TITLE
nf-core/rnaseq salmon count table leads to failure

### ISSUE THREAD

**Issue by d4straub** [qbic-pipelines/rnadeseq#54]
I used nf-core/rnaseq without STAR but with salmon. Also, I used a rather unusual .gff for bacterial with very limited information.

I could identify three problems:
- salmon output is csv instead of tsv.
- salmon produced rarely float numbers instead of integer. No idea why, this shouldnt happen imho.
- maybe because I used a non-emsembl .gff in combination with `--fc_group_features "transcript_id"` when running nf-core/rnaseq, the header looked like that:

transcript_id | QMFCE006AD
-- | --

instead of 

Geneid | gene_name | QBICK031A9Aligned.sortedByCoord.out.bam
-- | -- | --

I solved the problem by making csv to tsv, round floats to integer and changed header to 

Ensembl_ID | gene_name | QMFCE006AD
-- | -- | --

I am not sure the header is really required that way.

**Comment by ggabernet** [comment]
yes, the header is required that way, and the pipeline does not support salmon for now. Do you still need it?

**Comment by d4straub** [comment]
salmon accepted my gff, but I couldn't get to work STAR gene counts. So I had no choice.
For me, such small inconveniences are fine, maybe just state somewhere that salmon output isn't supported so that nobody else runs into this problem blindly.

**Comment by WackerO** [comment]
Closing this as salmon is now supported as well
