### ISSUE TITLE
Issue with whitespace in Heatmaps / Grouping names cannot have underscores

### ISSUE THREAD

**Issue by apeltzer** [qbic-pipelines/rnadeseq#57]
<img width="773" alt="Bildschirmfoto 2019-12-11 um 15 18 02" src="https://user-images.githubusercontent.com/2359510/70630575-15e9bd00-1c2c-11ea-8ed7-3aafd31c96bd.png">

**Comment by ggabernet** [comment]
I think this issue should be solved by now but let me know if you still experience problems
