### ISSUE TITLE
pathway analysis database version

### ISSUE THREAD

**Issue by ggabernet** [qbic-pipelines/rnadeseq#72]
- It would be great to track the version of the pathway analysis database to reproduce the results

**Comment by ggabernet** [comment]
- [ ] Getting a printed version of the databases used for pathway analysis in Milestone 2.0.1. Maybe the solution is [here](https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html#custom-data-sources-with-upload_gmt_file)
- [ ] In future release would be nice to have a way to provide any database version for reproducing the results.

**Comment by WackerO** [comment]
closing this as solved in #172
