### ISSUE TITLE
Parameter --kegg_blacklist does not work

### ISSUE THREAD

**Issue by LaurenceKuhl** [qbic-pipelines/rnadeseq#85]
When adding a kegg pathway with --kegg_blacklist, the pipeline runs but ignores the parameter. When I hardcoded the pathway [here](https://github.com/qbic-pipelines/rnadeseq/blob/abe742731af96ae25787f3a928a82cd4951d1a1d/bin/pathway_analysis.R#L20) it worked, so it is the append function  [here ](https://github.com/qbic-pipelines/rnadeseq/blob/abe742731af96ae25787f3a928a82cd4951d1a1d/bin/pathway_analysis.R#L66) causing the issue. 

Just creating a small issue so I have it noted somewhere, as soon as I have 5 minutes to test it out, I will fix this small bug :)
Thank you!
Laurence

**Comment by ggabernet** [comment]
Hi @LaurenceKuhl ,
did you have a chance to fix this or should I have a look into this?

**Comment by WackerO** [comment]
This should be fixed with https://github.com/qbic-pipelines/rnadeseq/pull/108 so I am closing this issue. If the bug appears again, please reopen!
