### ISSUE TITLE
Make --species optional if no pathway analysis is done

### ISSUE THREAD

**Issue by d4straub** [qbic-pipelines/rnadeseq#91]
Setting `--species` is not feasible for metatranscriptomics analysis. Because it is a mixture of species, i.e. bacterial community. This prevents running the pipeline with metatranscriptomics data.

Potential solutions:
-  if !params.species (or e.g. `--species "none"` or `--species "meta"`) than pathway analysis is skipped
- make `params.species` optional if pathway analysis is skipped (which is the case for metatranscriptomics anyway)

**Comment by WackerO** [comment]
I think this issue can be closed with the recent PR that made the pathway analysis skippable.
